### ISSUE TITLE
[error] tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

### ISSUE THREAD

**Issue by pumpkin007** [bennyguo/instant-nsr-pl#13]
Hi guys, thanks for the excellent work!

When I try the training code, I encountered the following error after Epoch 0 finished:

```
Global seed set to 42
Warning: FullyFusedMLP is not supported for the selected architecture 70. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 70. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
Global seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type      | Params
------------------------------------
0 | model | NeuSModel | 12.6 M
------------------------------------
12.6 M    Trainable params
0         Non-trainable params
12.6 M    Total params
25.220    Total estimated model params size (MB)
Epoch 0: : 10000it [06:59, 23.83it/s, loss=0.000965, train/inv_s=1.47e+3, train/num_rays=8192.0]                                                                                                          Traceback (most recent call last):                                                                                                                                                    | 0/2 [00:00<?, ?it/s]
  File "/home/zhouyiren/code/instant-nsr-pl/launch.py", line 123, in <module>
    main()
  File "/home/zhouyiren/code/instant-nsr-pl/launch.py", line 112, in main
    trainer.fit(system, datamodule=dm)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 241, in on_advance_end
    self._run_validation()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 299, in _run_validation
    self.val_loop.run()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 358, in validation_step
    return self.model(*args, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/pytorch_lightning/overrides/base.py", line 90, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/zhouyiren/code/instant-nsr-pl/systems/neus.py", line 137, in validation_step
    out = self(batch)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/code/instant-nsr-pl/systems/neus.py", line 46, in forward
    return self.model(batch['rays'])
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/code/instant-nsr-pl/models/neus.py", line 167, in forward
    out = chunk_batch(self.forward_, self.config.ray_chunk, rays)
  File "/home/zhouyiren/code/instant-nsr-pl/models/utils.py", line 22, in chunk_batch
    out_chunk = func(*[arg[i:i+chunk_size] if isinstance(arg, torch.Tensor) else arg for arg in args], **kwargs)
  File "/home/zhouyiren/code/instant-nsr-pl/models/neus.py", line 137, in forward_
    rgb, opacity, depth = rendering(
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/nerfacc/vol_rendering.py", line 115, in rendering
    rgbs, alphas = rgb_alpha_fn(t_starts, t_ends, ray_indices.long())
  File "/home/zhouyiren/code/instant-nsr-pl/models/neus.py", line 121, in rgb_alpha_fn
    rgb = self.texture(feature, t_dirs, normal)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/code/instant-nsr-pl/models/texture.py", line 26, in forward
    color = self.network(network_inp).view(*features.shape[:-1], self.n_output_dims).float()
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/tinycudann/modules.py", line 145, in forward
    output = _module_function.apply(
  File "/home/zhouyiren/anaconda3/envs/instant-nsr/lib/python3.10/site-packages/tinycudann/modules.py", line 57, in forward
    native_ctx, output = native_tcnn_module.fwd(input, params)
RuntimeError: /tmp/pip-req-build-8gaiqjyg/include/tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal
Epoch 0: : 10000it [07:05, 23.49it/s, loss=0.000965, train/inv_s=1.47e+3, train/num_rays=8192.0]
```

**Comment by bennyguo** [comment]
Hi! I used to encounter the same problem when using cutlass and haven't found out the reason.

You could simply replace all the `FullyFusedMLP` with `VanillaMLP` in the config yaml file (and the running efficiency won't be affected too much).

**Comment by pumpkin007** [comment]
> Hi! I used to encounter the same problem when using cutlass and haven't found out the reason.
> 
> You could simply replace all the `FullyFusedMLP` with `VanillaMLP` in the config yaml file (and the running efficiency won't be affected too much).

Hi @bennyguo, thanks a lot for the prompt reply! Now it is working fine:)
