### ISSUE TITLE
omegaconf.errors.missingmandatoryvalue:

### ISSUE THREAD

**Issue by anidealeft** [bennyguo/instant-nsr-pl#81]
when I try to do testing alone, such error occurs, could you please tell me how to fix the problem?
====================================================================
Traceback (most recent call last):
  File "launch.py", line 125, in <module>
    main()
  File "launch.py", line 52, in main
    config.exp_dir = config.get('exp_dir') or os.path.join(args.exp_dir, config.name)
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/opt/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: name
    full_key: name
    object_type=dict
===============================================================
the command I input is as such: 
python launch.py --config configs/neus-blender.yaml --resume exp/neus-blender-lego/ckpt/epoch=0-step=20000.ckpt --gpu 0 --test

**Comment by bennyguo** [comment]
If you do not use configs in the experiment directory (e.g., ` exp/neus-blender-lego/config/parsed.yaml`), you still need to specify the scene by `dataset.scene=xxx`, even if you resume from previous checkpoints :)

**Comment by anidealeft** [comment]
this makes efforts, thank you for your reply!
